name: Invoke Push

on:
  workflow_call:
    secrets:
      APP_ID:
        description: 'The ID of the GitHub App that can trigger a workflow on this repo'
        required: true
      APP_PRIVATE_KEY:
        description: 'The private key of the GitHub App that can trigger a workflow on this repo'
        required: true

jobs:
  invoke-push:
    runs-on: ubuntu-latest
    environment: invoke-push
    steps:
      - uses: actions/checkout@v2
      - run: npm i octokit
      - name: Trigger push workflow
        uses: actions/github-script@v6
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        with:
          result-encoding: string
          script: |
            const script = require('./.github/workflows/scripts/workflow.js')
            return await script({ core, exec })
