name: Invoke Push

on:
  workflow_call:
    secrets:
      APP_ID:
        description: 'The ID of the GitHub App that can trigger a workflow on this repo'
        required: true
      APP_PRIVATE_KEY:
        description: 'The private key of the GitHub App that can trigger a workflow on this repo'
        required: true

jobs:
  invoke-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v3
        with:
          repository: ljubon/charts
          path: charts
          ref: charts-master
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
      - run: npm i octokit @octokit/core node-fetch @octokit/rest @octokit/auth-app
      - name: Trigger push workflow
        uses: actions/github-script@v6.4.1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        with:
          retries: 3
          debug: true
          script: |
            const generateToken = require('./charts/.github/workflows/scripts/token.js')
            const workflow = require('./charts/.github/workflows/scripts/workflow.js')
            const tokenPermissions = { actions: "write" } // required
            try {
              const token = await generateToken({ core, fetch }, 'ljubon','charts', tokenPermissions )
            } catch (error) {
              core.notice(`Permission: ${JSON.stringify(tokenPermissions)}`)
              return core.setFailed(`Token - Unable to trigger workflow ljubon/charts, please check token permissions.\n${error}`)
            }

            try {
              return await workflow({ core, context, fetch }, token )
            } catch (error) {
              return core.setFailed(`Workflow - Unable to trigger workflow ljubon/charts, please check token permissions.\n${error}`)
            }