name: CI for Charts

on:
  push:
    branches: 
      - github-armada_*

jobs:
  createArmadaPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Armada Pull Request
        id: capr
        run: |
          RELEASE_TAG=`git branch --show-current | sed 's/github-armada_//'`
          hub pull-request -m "Update Armada Chart to $RELEASE_TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
