name: Charts

on: 
  push:
    branches:
      - 'master-update_*'
      - 'githubactions-armada_*'
      
jobs:
  update-gh-pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Update gh-pages - Armada
        if: ${{ github.ref, 'githubactions-armada_' }}
        run: |  
          RELEASE_TAG=`git branch --show-current | sed 's/githubactions-armada_//'`
          hub pull-request --base "gh-pages" -m "Update Armada Chart to $RELEASE_TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update gh-pages
        if: ${{ github.ref, 'master-update_' }}
        run: |
          helm repo index .
          hub pull-request --base "gh-pages" -m "Update Charts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}